language: rust

dist: xenial

rust:
  - stable
  - beta
  - nightly

os:
  - linux
  - osx
# by default, test vanilla setup on all three channels
env:
  global:
    - PROJ_FEATURES=""

# test both features on Linux stable, but only pkg_config on macOS stable
jobs:
  include:
    - os: linux
      env: PROJ_FEATURES="--features bundled_proj"
    - os: linux
      env: PROJ_FEATURES="--features pkg_config"
    - os: osx
      env: PROJ_FEATURES="--features pkg_config"

before_install:
  - |
    if [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$PROJ_FEATURES" != "bundled_proj" ]; then
      sudo apt-get update
      sudo apt-get -y install pkg-config
      wget https://download.osgeo.org/proj/proj-7.0.0.tar.gz
      tar -xzvf proj-7.0.0.tar.gz
      pushd proj-7.0.0 && ./configure --prefix=/usr && make && sudo make install && popd
    fi
  - |
    if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      brew update
      brew upgrade pkg-config
      brew upgrade proj
    fi

script:
  - cargo test $PROJ_FEATURES

cache: cargo
